services:
  jupyter-lab:
    build: ./jupyter_lab
    container_name: my-jupyter-lab
    ports:
      - "7777:8888"
    command: jupyter-lab --ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.notebook_dir='/jupyter/content'
    volumes:
      - ${PATH_TO_WD}:/jupyter/content
